name: lojongapp
description: lojongapp
version: 1.0.0+1

publish_to: none

environment:
  sdk: ^3.2.4
  flutter: ^3.16.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  chucker_flutter: ^1.6.2
  path_provider: ^2.1.2
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.9
  simple_animations: ^5.0.2
  share_plus: ^7.2.1
  refresh_loadmore: ^2.0.5
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/fonts/
  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/asap_400.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/asap_500_italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/asap_600.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/asap_700.ttf
          style: normal
          weight: 700
